set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN K2 [get_ports LED]
set_property PACKAGE_PIN V1 [get_ports reset_in]

set_property PACKAGE_PIN G6 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports B0_in]
set_property IOSTANDARD LVCMOS33 [get_ports B1_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Digital[6]}]
set_property PACKAGE_PIN D2 [get_ports {Digital[6]}]
set_property PACKAGE_PIN E2 [get_ports {Digital[5]}]
set_property PACKAGE_PIN F3 [get_ports {Digital[4]}]
set_property PACKAGE_PIN F4 [get_ports {Digital[3]}]
set_property PACKAGE_PIN D3 [get_ports {Digital[2]}]
set_property PACKAGE_PIN E3 [get_ports {Digital[1]}]
set_property PACKAGE_PIN D4 [get_ports {Digital[0]}]

set_property PACKAGE_PIN F6 [get_ports LED_2]
set_property PACKAGE_PIN G4 [get_ports LED_3]
set_property PACKAGE_PIN G3 [get_ports LED_4]
set_property PACKAGE_PIN J3 [get_ports LED_5]
set_property IOSTANDARD LVCMOS33 [get_ports LED_2]
set_property IOSTANDARD LVCMOS33 [get_ports LED_3]
set_property IOSTANDARD LVCMOS33 [get_ports LED_5]
set_property IOSTANDARD LVCMOS33 [get_ports LED_4]


set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN R11 [get_ports reset]
set_property PACKAGE_PIN R17 [get_ports B0_in]
set_property PACKAGE_PIN R15 [get_ports B1_in]
